# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.
name: Release to Charmhub

on:
  push:
    branches:
      - main
      - spark-integration

jobs:
  ci-tests:
    name: Tests
    uses: ./.github/workflows/ci.yaml
    secrets: inherit
    permissions:
      contents: write  # Needed for Allure Report beta

  release:
    name: Release charm to test branch
    needs:
      - ci-tests
    uses: canonical/data-platform-workflows/.github/workflows/release_charm_pr.yaml@v32.1.0
    with:
      track: "1"
      artifact-prefix: ${{ needs.ci-tests.outputs.artifact-prefix }}
    secrets:
      charmhub-token: ${{ secrets.CHARMHUB_TOKEN }}